import { StyleSheet } from "react-native";
import { RFPercentage, RFValue } from "react-native-responsive-fontsize";

const colorPrimary = "#0e4e92"; //blue

//font_weight
const extralight = "commi_extralight";
const bold = "cereal_bold";
const extrabold = "commi_extrabold";
const light = "cereal_light";
const medium = "cereal_medium";
const regular = "cereal_regular";
const semibold = "cereal_medium";

export default StyleSheet.create({
  listingDetailsDescM: {
    fontSize: RFValue(13),
    color: "gray",
    fontFamily: regular,
    marginTop: 0,
    lineHeight: 30,
    textAlign: "right",
  },
  listingDetailsM: {
    fontSize: RFValue(13),
    color: colorPrimary,
    fontFamily: medium,
    marginTop: 0,
    lineHeight: 30,
    textAlign: "left",
  },
  listingVehicleTextM: {
    fontSize: RFValue(15),
    color: "#555555",
    fontFamily: medium,
    marginTop: 0,
    lineHeight: 30,
    textAlign: "left",
  },
  listingPriceBoldM: {
    fontSize: RFValue(17),
    fontFamily: medium,
    color: colorPrimary,
    textAlign: "right",
  },
  listingPriceM: {
    fontSize: RFValue(15),
    fontFamily: regular,
    color: colorPrimary,
    textAlign: "right",
  },
  listingNameM: {
    fontFamily: regular,
    color: "#3e3e3e",
    fontSize: RFValue(15),
  },
  listingRegionM: {
    fontFamily: regular,
    color: "#3e3e3e",
    fontSize: RFValue(10),
    marginTop: 3,
  },
  listingTimeM: {
    fontFamily: regular,
    color: "gray",
    fontSize: RFValue(10),
    marginTop: 3,
  },

  //New Desing
  containerM: {
    width: "100%",
    paddingHorizontal: 20,
    marginTop: 30,
  },
  textHeaderM: {
    fontSize: RFValue(19),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 0,
    lineHeight: 30,
    textAlign: "left",
    width: "100%",
  },
  textHeaderMNZTA: {
    fontSize: RFValue(18),
    color: "gray",
    fontFamily: semibold,
    marginTop: 40,
    lineHeight: 30,
    textAlign: "left",
  },
  textHeaderScreenM: {
    fontSize: RFValue(18),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 0,
    lineHeight: 30,
    textAlign: "left",
  },
  textHeaderScreenMBalck: {
    fontSize: RFValue(18),
    color: "black",
    fontFamily: semibold,
    marginTop: 0,
    lineHeight: 30,
    textAlign: "left",
  },
  textHeaderModalM: {
    fontSize: RFValue(17),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 0,
    lineHeight: 20,
    textAlign: "left",
  },
  textSubModalM: {
    fontSize: RFValue(15),
    color: "gray",
    fontFamily: regular,
    marginTop: 0,
    lineHeight: 20,
    textAlign: "left",
  },
  textSubM: {
    fontFamily: regular,
    color: "gray",
    textAlign: "left",
    fontSize: RFValue(15),
    marginTop: 30,
    lineHeight: 26,
  },
  textSubMDownload: {
    fontFamily: regular,
    color: colorPrimary,
    textAlign: "center",
    fontSize: RFValue(15),
    marginTop: 30,
    lineHeight: 26,
    width: "100%",
  },
  textSubMLinks: {
    fontFamily: regular,
    color: colorPrimary,
    textAlign: "left",
    fontSize: RFValue(15),
    marginTop: 26,
    lineHeight: 26,
  },
  buttonM: {
    height: 50,
    backgroundColor: colorPrimary,
    alignItems: "center",
    zIndex: 1000,
    width: "100%",
    borderRadius: 50,
  },
  buttonTextM: {
    textAlignVertical: "center",
    color: "white",
    fontSize: 18,
    marginTop: 13,
    fontFamily: medium,
  },
  buttonTextM2: {
    textAlignVertical: "center",
    color: "#808080bf",
    fontSize: 18,
    marginTop: 13,
    fontFamily: light,
  },
  buttonTextBanner: {
    textAlignVertical: "center",
    color: "white",
    fontSize: 13,
    marginTop: 5,
    fontFamily: medium,
  },
  textHeaderMCenter: {
    fontSize: RFValue(18),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 120,
    lineHeight: 30,
    textAlign: "center",
  },
  textHeaderMCenter2: {
    fontSize: RFValue(18),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 60,
    lineHeight: 30,
    textAlign: "left",
    marginStart: 20,
  },
  textHeaderMCenter3: {
    fontSize: RFValue(18),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: -80,
    lineHeight: 30,
    textAlign: "left",
    marginStart: 20,
  },
  textSubMCenter2: {
    fontFamily: regular,
    color: "gray",
    textAlign: "left",
    fontSize: RFValue(15),
    marginTop: 10,
    lineHeight: 26,
    marginStart: 20,
  },
  textSubMCenter3: {
    fontFamily: regular,
    color: "gray",
    textAlign: "left",
    fontSize: RFValue(15),
    marginTop: 5,
    lineHeight: 26,
    marginStart: 20,
    marginBottom: 20,
  },
  textSubMCenter: {
    fontFamily: regular,
    color: "gray",
    textAlign: "center",
    fontSize: RFValue(15),
    marginTop: 20,
    lineHeight: 26,
  },
  buttonViewM: {
    backgroundColor: colorPrimary,
    marginTop: 20,
    height: 35,
    borderRadius: 20,
    alignItems: "center",
    marginHorizontal: 5,
    zIndex: 1000,
    flexDirection: "row",
    justifyContent: "center",
  },
  buttonViewWhiteM: {
    backgroundColor: "#e5e6eb",
    marginTop: 20,
    height: 35,
    borderRadius: 20,
    alignItems: "center",
    marginHorizontal: 5,
    flexDirection: "row",
    justifyContent: "center",
  },
  buttonViewWhiteF: {
    backgroundColor: "transparent",
    marginTop: 20,
    height: 35,
    borderRadius: 20,
    alignItems: "center",
    marginHorizontal: 5,
    flexDirection: "row",
    justifyContent: "center",
    borderColor: "gray",
    borderWidth: 1,
  },
  buttonViewWhiteF2: {
    backgroundColor: "#bdd5ed",
    marginTop: 20,
    height: 35,
    borderRadius: 20,
    alignItems: "center",
    marginHorizontal: 5,
    flexDirection: "row",
    justifyContent: "center",
    borderColor: colorPrimary,
    borderWidth: 1,
  },
  buttonTextNearM: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 0,
    fontFamily: regular,
    marginHorizontal: 25,
    fontSize: RFValue(15),
  },
  buttonTextWhiteF: {
    textAlignVertical: "center",
    color: "gray",
    marginTop: 0,
    fontFamily: regular,
    marginHorizontal: 25,
    fontSize: RFValue(15),
  },
  buttonTextWhiteF2: {
    textAlignVertical: "center",
    color: colorPrimary,
    marginTop: 0,
    fontFamily: regular,
    marginHorizontal: 25,
    fontSize: RFValue(15),
 
  },
  buttonTextWhiteM: {
    textAlignVertical: "center",
    color: "black",
    marginTop: 0,
    fontFamily: regular,
    marginHorizontal: 25,
    fontSize: RFValue(15),
  },
  titleListingM: {
    fontSize: RFValue(14),
    color: colorPrimary,
    fontFamily: bold,
    marginTop: 0,
    lineHeight: 20,
    textAlign: "left",
  },
  subTitleListingM: {
    fontFamily: regular,
    color: "black",
    //fontSize:15
    fontSize: RFValue(14),
  },
  smallTitleListingM: {
    fontSize: RFValue(11),
    fontFamily: regular,
    marginTop: 5,
    textAlign: "right",
    color: "gray",
  },
  textInputM: {
    height: 50,
    width: "98%",
    paddingHorizontal: 15,
    backgroundColor: "#f2f2f2",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    color: "gray",
    fontFamily: regular,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 40,
    fontSize: 16,
  },
  textInputSelectedM: {
    height: 50,
    width: "98%",
    paddingHorizontal: 15,
    backgroundColor: "#f2f2f2",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    color: "gray",
    fontFamily: regular,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 40,
    fontSize: 16,
  },
  menuTitleM: {
    color: colorPrimary,
    marginTop: 0,
    fontSize: RFValue(14),
    fontFamily: medium,
  },
  menuSubTitleM: {
    color: "gray",
    marginTop: 10,
    fontSize: RFValue(13),
    fontFamily: regular,
  },
  buttonHomeM: {
    height: 55,
    backgroundColor: "white",
    alignItems: "center",
    zIndex: 1000,
    width: "100%",
    borderRadius: 5,
  },
  buttonTextHomeM: {
    textAlignVertical: "center",
    color: colorPrimary,
    fontSize: 18,
    marginTop: 15,
    fontFamily: medium,
  },
  categoryTextM: {
    paddingHorizontal: 30,
    paddingVertical: 10,
    fontFamily: regular,
    color: "black",
    fontSize: RFValue(14),
  },
  categoryTextSelectedM: {
    marginHorizontal: 15,
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontFamily: bold,
    color: colorPrimary,
    borderBottomColor: colorPrimary,
    borderBottomWidth: 1.5,
    fontSize: RFValue(15),
  },
  bottomTextM: {
    fontSize: 10,
    fontFamily: regular,
    marginTop: 3,
  },
  containerPopup: {
    flex: 1,
    paddingTop: 30,
    marginHorizontal: 0,
    alignItems: "flex-start",
    backgroundColor: "#f2f2f2",
    paddingHorizontal: 15,
    marginBottom: -30,
  },

  scrollingBackground: {
    backgroundColor: "transparent",
  },
  contactText: {
    color: "white",
    alignSelf: "center",
    marginTop: 10,
    fontSize: 30,
    fontFamily: semibold,
  },
  menuTitle: {
    color: "gray",
    marginTop: 0,
    fontSize: RFValue(12),
    fontFamily: regular,
  },

  menuSubTitle: {
    color: "black",
    marginTop: 10,
    fontSize: RFValue(14),
    fontFamily: semibold,
  },

  newsButtons: {
    textAlign: "center",
    color: "gray",
    fontFamily: semibold,
    fontSize: 13,
  },

  newsButtonsLiked: {
    textAlign: "center",
    color: colorPrimary,
    fontFamily: semibold,
    fontSize: 13,
  },

  divNewListing: {
    backgroundColor: colorPrimary,
    padding: 15,
    borderRadius: 30,
    marginBottom: 40,
    width: 50,
    height: 50,
    alignSelf: "center",
  },

  buttonNewListing: {
    width: 20,
    height: 20,
    alignSelf: "center",
  },

  containerFullScreen: {
    flex: 1,
    alignItems: "flex-start",
    backgroundColor: "#f2f2f2",
  },

  container: {
    flex: 1,
    paddingTop: 60,
    marginHorizontal: 0,
    alignItems: "flex-start",
    backgroundColor: "#f2f2f2",
    paddingHorizontal: 15,
    marginBottom: -30,
  },

  containerWhite: {
    flex: 1,
    paddingTop: 60,
    marginHorizontal: 0,
    alignItems: "flex-start",
    backgroundColor: "white",
    paddingHorizontal: 15,
    marginBottom: -30,
  },

  containerWhiteAvoid: {
    flex: 1,
    paddingTop: 60,
    marginHorizontal: 0,
    backgroundColor: "white",
    paddingHorizontal: 15,
    marginBottom: -30,
  },

  container2: {
    flex: 1,
    paddingTop: 60,
    marginHorizontal: 0,
    alignItems: "flex-start",
    backgroundColor: "#f2f2f2",
    paddingHorizontal: 15,
    marginBottom: -30,
  },

  containerResult: {
    flex: 1,
    marginTop: 60,
    marginHorizontal: 15,
    alignItems: "flex-start",
    backgroundColor: "#f2f2f2",
    paddingHorizontal: 15,
  },
  container1: {
    flexDirection: "row",
    marginTop: 60,
    marginHorizontal: 15,
    alignItems: "flex-start",
    backgroundColor: "#f2f2f2",
    paddingHorizontal: 15,
  },

  viewHeader: {
    flex: 1,
  },

  viewContent: {
    flex: 10,
  },
  TextCardListView: {
    fontFamily: medium,
    color: "#3e3e3e",
    fontSize: RFValue(13),
  },
  SubTextCardListView: {
    fontFamily: medium,
    color: colorPrimary,
    textAlign: "right",
  },

  dealerNameSearch: {
    fontFamily: medium,
    color: "#3e3e3e",
    fontSize: 14,
  },

  contactNameSearch: {
    fontFamily: medium,
    color: "#3e3e3e",
    fontSize: 16,
  },
  contactRegionSearch: {
    fontFamily: regular,
    color: "#3e3e3e",
    fontSize: 12,
    marginTop: 3,
  },
  emailcontactRegionSearch: {
    fontFamily: regular,
    color: colorPrimary,
    fontSize: 12,
    marginTop: 3,
  },
  dealerRegionSearch: {
    fontFamily: regular,
    color: "#3e3e3e",
    fontSize: 12,
    marginTop: 3,
  },
  TextCardVehicle: {
    fontFamily: regular,
    marginTop: 3,
    color: "gray",
  },
  TextCardVehicleDate: {
    fontFamily: regular,
    marginTop: 5,
    fontSize: 11,
    textAlign: "right",
    color: "gray",
  },
  TextCardMyDocumentDate: {
    fontFamily: regular,
    marginTop: 5,
    fontSize: 13,
    textAlign: "left",
    color: colorPrimary,
  },
  TextCard: {
    fontFamily: regular,
    color: "black",
  },
  TextCardN: {
    fontSize: 16,
    fontFamily: medium,
    color: "black",
  },
  subTextCardN: {
    fontFamily: regular,
    color: "gray",
    marginTop: 7,
    fontSize: 12,
  },

  subTextCardL: {
    fontFamily: medium,
    color: "gray",
    marginTop: -3,
    fontSize: 13,
    alignSelf: "flex-end",
  },

  subTextCardDistance: {
    fontFamily: medium,
    color: "gray",
    marginTop: 13,
    fontSize: 14,
    alignSelf: "flex-end",
  },

  subTextCard: {
    fontFamily: regular,
    color: colorPrimary,
    marginTop: 5,
  },

  subTextCardVehicleReport: {
    fontFamily: bold,
    color: "black",
    //fontSize:15
    fontSize: RFValue(14),
  },

  subTextCardVehicle: {
    fontFamily: bold,
    color: colorPrimary,
    //fontSize:15
    fontSize: RFValue(14),
  },

  myVehicleSub: {
    fontFamily: medium,
    color: colorPrimary,
    //fontSize:15
    fontSize: RFValue(14),
    textAlign: "center",
  },
  myVehicleSubExpire: {
    fontFamily: medium,
    color: "#bd0000",
    //fontSize:15
    fontSize: RFValue(14),
    textAlign: "center",
    marginTop: 10,
  },
  myVehicleSubExpireMonth: {
    fontFamily: medium,
    color: "#c29f1b",
    //fontSize:15
    fontSize: RFValue(14),
    textAlign: "center",
    marginTop: 10,
  },
  myVehicleSubRigth: {
    fontFamily: medium,
    textAlign: "center",
    color: "gray",
    //fontSize:15
    fontSize: RFValue(14),
  },
  myVehicleSubRigthExpire: {
    fontFamily: medium,
    textAlign: "center",
    color: "#bd0000",
    //fontSize:15
    fontSize: RFValue(14),
    marginTop: 10,
  },
  myVehicleSubRigthExpireMonth: {
    fontFamily: medium,
    textAlign: "center",
    color: "#c29f1b",
    marginTop: 10,
    //fontSize:15
    fontSize: RFValue(14),
  },

  subTextNearby: {
    fontFamily: regular,
    color: "gray",
    fontSize: 12,
  },
  subTextVehicleDetails: {
    fontFamily: medium,
    color: "black",
  },
  subText: {
    fontFamily: regular,
    color: "gray",
  },
  subTextVehicle: {
    fontFamily: medium,
    color: "gray",
  },
  subTextDetails: {
    fontFamily: medium,
    color: "gray",
  },
  subTextMake: {
    fontFamily: regular,
    color: "gray",
    textAlign: "center",
    fontSize: 13,
  },
  subTextMakeSplash: {
    fontFamily: semibold,
    color: "gray",
    textAlign: "center",
    fontSize: RFValue(15),
  },
  subTextMakeList: {
    fontFamily: semibold,
    color: "gray",
    textAlign: "left",
    fontSize: 13,
    marginStart: 12,
  },

  subTextMakeList2: {
    fontFamily: semibold,
    color: "gray",
    textAlign: "left",
    fontSize: 13,
    marginTop: 2,
  },

  menuTitleBox: {
    fontFamily: regular,
    color: "gray",
    textAlign: "left",
    fontSize: 13,
  },
  daysAgoSearch: {
    fontFamily: medium,
    color: "gray",
    textAlign: "right",
    fontSize: 10,
    marginStart: 12,
  },
  subTextMakeN: {
    fontFamily: regular,
    color: "#a1a1a1",
    textAlign: "center",
    fontSize: 16,
    marginTop: 18,
  },
  gridHeader: {},
  textHeader: {
    fontSize: RFValue(22),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 0,
  },
  textHeaderModal: {
    textAlign: "center",
    width: "100%",
    fontSize: RFValue(22),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 0,
  },
  textHeaderSplash: {
    fontSize: RFValue(20),
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 30,
    lineHeight: 20,
    textAlign: "center",
  },
  textHeaderDetails: {
    color: colorPrimary,
    fontFamily: regular,
    marginTop: 3,
  },
  textHeaderLoading: {
    fontSize: 25,
    color: "white",
    fontFamily: semibold,
    textAlign: "center",
    marginTop: 3,
    alignSelf: "center",
  },
  lottieTitle: {
    fontSize: 20,
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: -80,
    textAlign: "center",
  },
  lottieTitle2: {
    fontSize: 20,
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: -30,
    textAlign: "center",
  },
  lottieSub: {
    fontFamily: medium,
    color: "gray",
    textAlign: "center",
    width: "100%",
    marginTop: 10,
    fontSize: 13,
  },
  textHeaderBlack: { fontSize: 25, color: "white", fontFamily: semibold },
  textSubHeader: { fontSize: 16, color: colorPrimary, fontFamily: medium }, //18
  textSubHeader2: {
    fontSize: 16,
    color: colorPrimary,
    fontFamily: medium,
    marginTop: 20,
  },
  item: {
    margin: 0,
    marginBottom: 20,
    width: "100%",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    shadowOpacity: 0, //default is 1
    shadowRadius: 0, //default is 1
    borderWidth: 1, // Remove Border
  },

  buttonLigthView: {
    backgroundColor: "#a0afcd",
    marginTop: 20,
    height: 40,
    borderRadius: 50,
    alignItems: "center",
    marginHorizontal: 2,
    zIndex: 1000,
  },

  buttonLigthViewNo: {
    backgroundColor: "#e4e5e7",
    marginTop: 20,
    height: 40,
    borderRadius: 50,
    alignItems: "center",
    marginHorizontal: 2,
    zIndex: 1000,
  },

  buttonTextLight: {
    textAlignVertical: "center",
    color: "#426093",
    marginTop: 10,
    fontFamily: medium,
  },

  buttonTextLightNo: {
    textAlignVertical: "center",
    color: "#a3a6a7",
    marginTop: 10,
    fontFamily: medium,
  },

  buttonView: {
    backgroundColor: colorPrimary,
    marginTop: 20,
    height: 50,
    borderRadius: 5,
    alignItems: "center",
    marginHorizontal: 2,
    zIndex: 1000,
  },

  buttonViewUploadFoto: {
    backgroundColor: "white",
    borderColor: colorPrimary,
    borderWidth: 1,
    marginTop: 40,
    height: 40,
    borderRadius: 5,
    alignItems: "center",
    zIndex: 1000,
    width: "100%",
  },

  buttonViewHomeScreen: {
    backgroundColor: colorPrimary,
    marginTop: 20,
    height: 55,
    borderRadius: 5,
    alignItems: "flex-start",
    marginHorizontal: 2,
    zIndex: 1000,
  },

  buttonViewC: {
    backgroundColor: colorPrimary,
    marginTop: 20,
    height: 50,
    borderRadius: 5,
    alignItems: "center",
    marginHorizontal: 2,
    zIndex: 1000,
    width: "100%",
  },
  viewDealer: {
    height: 55,
    backgroundColor: colorPrimary,
    alignItems: "center",
    zIndex: 1000,
    width: "100%",
    borderRadius: 5,
  },
  viewDealerNew: {
    height: 50,
    backgroundColor: colorPrimary,
    alignItems: "center",
    zIndex: 1000,
    width: "100%",
    borderRadius: 5,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
  },
  viewDealerUpdate: {
    height: 55,
    backgroundColor: colorPrimary,
    alignItems: "center",
    zIndex: 1000,
    width: "100%",
    borderRadius: 15,
  },
  viewDealerRed: {
    backgroundColor: "#BD362F",
    alignItems: "center",
    zIndex: 1000,
    width: "100%",
    borderRadius: 15,
  },
  viewDealerUpdateRed: {
    height: 55,
    backgroundColor: "gray",
    alignItems: "center",
    zIndex: 1000,
    width: "100%",
    borderRadius: 15,
  },

  // Dealership inside Desing ******************+
  subTextDealer: {
    fontFamily: medium,
    color: "gray",
    marginTop: 5,
  },
  subTextDealer2: {
    fontFamily: regular,
    color: "gray",
    marginTop: 5,
  },
  buttonViewDealerWhite: {
    backgroundColor: "#f0f1f5",
    borderColor: "#e4e5ea",
    borderWidth: 1,
    marginTop: 5,
    height: 35,
    borderRadius: 3,
    width: "100%",
    paddingHorizontal: 5,
    zIndex: 1000,
  },
  textHeaderDealer: {
    fontSize: 20,
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 8,
  },
  textHeaderDealer2: {
    fontSize: 12,
    color: colorPrimary,
    fontFamily: semibold,
    marginTop: 8,
  },
  buttonViewDealer: {
    backgroundColor: colorPrimary,
    marginTop: 5,
    height: 35,
    borderRadius: 3,
    width: "100%",
    paddingHorizontal: 5,
    zIndex: 1000,
  },
  buttonTextDealer: {
    textAlignVertical: "center",
    width: "100%",
    textAlign: "center",
    color: "white",
    marginTop: 0,
    fontSize: 15,
    fontFamily: medium,
  },

  buttonTextDealerWhite: {
    textAlignVertical: "center",
    width: "100%",
    textAlign: "center",
    color: "gray",
    marginTop: 0,
    fontSize: 15,
    fontFamily: medium,
  },

  tabTextSelect: {
    textAlign: "center",
    marginBottom: 0,
    color: "#0e4e92",
    fontFamily: bold,
    height: 40,
  },
  tabText: {
    textAlign: "center",
    marginBottom: 0,
    fontFamily: regular,
    color: "black",
    height: 40,
  },
  tabViewSelect: {
    borderBottomWidth: 2,
    borderColor: "#0e4e92",
  },
  tabViewSelectS: {
    borderBottomWidth: 2,
    borderColor: "#0e4e92",
    marginHorizontal: -15,
  },

  tabView: {
    textAlign: "center",
    marginBottom: 0,
    height: 40,
  },
  tabViewS: {
    textAlign: "center",
    marginBottom: 0,
    marginHorizontal: -15,
    height: 40,
  },

  //*************+++++++ */

  // Nearby Design **************

  modalText: {
    fontFamily: regular,
    color: "white",
    textAlign: "center",
    fontSize: 16,
    marginTop: 7,
  },

  modalTextN: {
    fontFamily: regular,
    color: "gray",
    textAlign: "center",
    fontSize: 16,
    marginTop: 7,
  },

  iconN: {
    color: "white",
    width: 16,
    marginStart: 12,
  },

  iconNW: {
    color: "black",
    width: 16,
    marginStart: 12,
  },

  buttonViewTraffic: {
    backgroundColor: "white",
    height: 35,
    width: 35,
    marginEnd: 15,
    borderRadius: 20,
    alignItems: "center",
    zIndex: 1000,
    flexDirection: "row",
    justifyContent: "center",
  },

  buttonViewNearby: {
    backgroundColor: colorPrimary,
    marginTop: 20,
    height: 35,
    borderRadius: 20,
    alignItems: "center",
    marginHorizontal: 5,
    zIndex: 1000,
    flexDirection: "row",
    justifyContent: "center",
  },

  buttonViewN: {
    backgroundColor: colorPrimary,
    marginTop: 20,
    height: 45,
    borderRadius: 20,
    alignItems: "center",
    marginHorizontal: 5,
    zIndex: 1000,
    flexDirection: "row",
    justifyContent: "center",
  },

  buttonTextNearOld: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 0,
    fontFamily: medium,
    marginHorizontal: 15,
  },

  buttonTextWhiteOld: {
    textAlignVertical: "center",
    color: "black",
    marginTop: 0,
    fontFamily: regular,
    marginHorizontal: 15,
  },

  buttonViewWhiteNearby: {
    backgroundColor: "#e5e6eb",
    marginTop: 20,
    height: 35,
    borderRadius: 20,
    alignItems: "center",
    marginHorizontal: 5,
    flexDirection: "row",
    justifyContent: "center",
  },

  buttonViewWhiteN: {
    backgroundColor: "white",
    marginTop: 20,
    height: 45,
    width: 45,
    borderRadius: 30,
    alignItems: "center",
    marginHorizontal: 5,
    flexDirection: "row",
    justifyContent: "center",
    borderColor: colorPrimary,
    borderWidth: 2,
    alignSelf: "center",
  },

  buttonTextNear: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 0,
    fontFamily: bold,
    marginHorizontal: 16,
  },

  buttonTextNearTraffic: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 0,
    fontFamily: medium,
  },

  buttonTextNearTrafficRegion: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 2,
    fontFamily: medium,
  },
  buttonTextWhiteNRegion: {
    textAlignVertical: "center",
    alignContent: "center",
    color: colorPrimary,
    marginTop: 2,
    fontFamily: regular,
    marginHorizontal: 15,
  },

  buttonTextN: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 0,
    fontFamily: medium,
  },

  buttonTextWhiteN: {
    textAlignVertical: "center",
    alignContent: "center",
    color: "black",
    marginTop: 0,
    fontFamily: regular,
  },

  iconBackN: {
    alignItems: "center",
    backgroundColor: "white",
    margin: 5,
    borderRadius: 5,
    height: 60,
  },
  iconBackSelectedN: {
    alignItems: "center",
    backgroundColor: "#0e4e9214",
    margin: 5,
    borderRadius: 5,
    borderColor: colorPrimary,
    borderWidth: 0.6,
    height: 60,
  },
  modaliconBackN: {
    alignItems: "center",
    backgroundColor: "white",
    margin: 5,
    borderRadius: 55,
    height: 35,
  },
  modaliconBackSelectedN: {
    alignItems: "center",
    backgroundColor: colorPrimary,
    margin: 5,
    borderRadius: 55,
    borderColor: colorPrimary,
    borderWidth: 0.6,
    height: 35,
  },
  buttonViewWhiteNearDone: {
    backgroundColor: colorPrimary,
    marginTop: 10,
    height: 50,
    borderRadius: 50,
    alignItems: "center",
    marginHorizontal: 5,
  },
  // End Nearby Design **********
  modaliconBackSelectedNTraffic: {
    alignItems: "center",
    backgroundColor: colorPrimary,
    margin: 5,
    borderRadius: 5,
    borderColor: colorPrimary,
    borderWidth: 0.6,
    height: 45,
    width: "100%",
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  modaliconBackNTraffic: {
    alignItems: "center",
    backgroundColor: "white",
    margin: 5,
    borderRadius: 5,
    borderColor: colorPrimary,
    borderWidth: 0.6,
    height: 45,
    width: "100%",
    paddingVertical: 10,
    paddingHorizontal: 10,
  },

  buttonTextUploadImage: {
    textAlignVertical: "center",
    color: colorPrimary,
    marginTop: 11,
    fontFamily: medium,
  },

  buttonText: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 15,
    fontFamily: medium,
    fontSize: 16,
  },
  buttonTextC: {
    textAlignVertical: "center",
    color: "white",
    fontSize: 18,
    marginTop: 15,
    fontFamily: medium,
  },
  buttonTextNew: {
    textAlignVertical: "center",
    color: "white",
    fontSize: 18,
    marginTop: 15,
    fontFamily: medium,
  },
  buttonTextHome: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 17,
    fontSize: 16,
    fontFamily: medium,
    alignSelf: "center",
  },

  buttonViewWhite: {
    backgroundColor: "white",
    marginTop: 10,
    height: 50,
    borderRadius: 5,
    alignItems: "center",
    marginHorizontal: 5,
  },
  buttonViewWhite2: {
    backgroundColor: "white",
    marginTop: 20,
    height: 40,
    borderRadius: 5,
    alignItems: "center",
    marginHorizontal: 5,
  },
  buttonTextWhite: {
    textAlignVertical: "center",
    color: colorPrimary,
    marginTop: 14,
    fontFamily: medium,
  },
  buttonViewU: {
    backgroundColor: colorPrimary,
    marginTop: 20,
    height: 50,
    borderRadius: 5,
    alignItems: "center",
  },
  buttonTextU: {
    textAlignVertical: "center",
    color: "white",
    marginTop: 15,
    fontFamily: medium,
  },

  textInput: {
    height: 50,
    width: "100%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
  },
  textInputUnder: {
    height: 40,
    width: "100%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
    marginTop: 25,
  },
  textInputInvalidate: {
    height: 40,
    width: "100%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#ed4d4d",
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
  },
  textInputInvalidateUnder: {
    height: 40,
    width: "100%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#ed4d4d",
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
    marginTop: 25,
  },
  textInputRowSplash: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#dadada",
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    marginTop: 20,
  },
  textInputRow: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#dadada",
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
  },
  textInputRowD: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "#EBEBEB",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    color: "gray",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  textInputRowDesc: {
    textAlignVertical: "top",
    height: 300,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#dadada",
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
    paddingTop: 10,
  },
  textInputRowSelected: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: colorPrimary,
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
  },
  textInputRowSelectedPlace: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: colorPrimary,
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    marginTop: 20,
  },
  textInputRowSelectedDesc: {
    textAlignVertical: "top",
    height: 300,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: colorPrimary,
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
    paddingTop: 10,
  },
  textInputRow2: {
    height: 35,
    marginTop: 4,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
  },
  textInputdesc: {
    height: 135,
    marginTop: 4,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
  },
  textInputdescUpdate: {
    height: 200,
    marginTop: 4,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
    borderRadius: 5,
  },
  cardTitle: {
    fontFamily: medium,
  },
  cardSubtitle: {
    fontFamily: regular,
    fontSize: 15,
    marginTop: 5,
    color: "black",
  },
  titleInputRego: {
    fontFamily: medium,
    color: "gray",
    marginTop: 50,
    fontSize: 16,
    marginHorizontal: 5,
  },
  titleInput: {
    fontFamily: medium,
    color: "gray",
    marginTop: 25,
    marginHorizontal: 5,
    fontSize: RFValue(13),
  },
  titleInputBox: {
    fontFamily: bold,
    color: colorPrimary,
    marginTop: 25,
    marginHorizontal: 5,
    fontSize: RFValue(16),
  },

  checkBoxTitle: {
    fontFamily: regular,
    color: "gray",
    marginStart: 5,
    fontSize: 15,
    marginTop: 0,
    alignContent: "center",
    textAlignVertical: "center",
  },

  titleInput3: {
    fontFamily: medium,
    color: "gray",
    marginTop: 5,
    marginHorizontal: 5,
  },
  titleInput2: {
    fontFamily: medium,
    color: "gray",
    marginEnd: 3,
    marginTop: 16,
    textAlign: "center",
  },
  h1Title: {
    fontFamily: regular,
    color: "gray",
    marginTop: 25,
    marginHorizontal: 5,
    fontSize: 18,
  },
  h1TitlePopup: {
    fontFamily: regular,
    color: "gray",
    marginTop: -5,
    marginStart: -15,
    fontSize: 18,
  },

  txtDesc: {
    fontFamily: regular,
    color: "gray",
    marginTop: 3,
    marginHorizontal: 5,
  },
  txtDesc2: {
    fontFamily: regular,
    color: "gray",
    marginTop: 3,
    marginStart: -15,
  },
  fullScreenImage: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
  },
  modalBottom: {
    margin: 0,
    backgroundColor: "white",
    height: 300,
    flex: 0,
    bottom: 0,
    position: "absolute",
    width: "100%",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  labelPlaceholder: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#dadada",
    shadowOpacity: 0,
    color: "#d4d3d9",
    shadowRadius: 0,
    paddingTop: 15,
    fontFamily: medium,
    overflow: "hidden",
    borderRadius: 5,
  },
  labelPlaceholderPicker: {
    height: 40,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    shadowOpacity: 0,
    color: "gray",
    shadowRadius: 0,
    borderRadius: 15,
    paddingTop: 20,
    marginTop: 10,
    fontFamily: medium,
    overflow: "hidden",
  },
  labelPlaceholder2: {
    height: 50,
    width: "95%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    shadowOpacity: 0,
    color: "gray",
    shadowRadius: 0,
    borderRadius: 5,
    paddingTop: 15,
    fontFamily: light,
    overflow: "hidden",
  },
  labelText2: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    shadowOpacity: 0,
    color: "#343434",
    shadowRadius: 0,
    borderRadius: 5,
    paddingTop: 15,
    fontFamily: light,
    overflow: "hidden",
  },
  labelPlaceholderUn: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "#4a4a4a14",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    shadowOpacity: 0,
    color: "gray",
    shadowRadius: 0,
    borderRadius: 5,
    paddingTop: 15,
    fontFamily: light,
    overflow: "hidden",
  },
  labelText: {
    height: 50,
    width: "98%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#dadada",
    shadowOpacity: 0,
    color: "#343434",
    shadowRadius: 0,
    paddingTop: 15,
    fontFamily: medium,
    overflow: "hidden",
    borderRadius: 5,
  },
  textPlaceholder: {
    color: "#343434",
    fontFamily: light,
  },
  SectionStyle: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 0.5,
    borderColor: "#000",
    height: 40,
    borderRadius: 5,
    margin: 10,
  },
  ImageStyle: {
    padding: 10,
    margin: 5,
    height: 25,
    width: 25,
    resizeMode: "stretch",
    alignItems: "center",
  },
  checkBoxTxt: {
    marginLeft: 10,
    marginTop: 0,
    fontSize: 20,
    alignContent: "flex-start",
  },
  iconBack: {
    alignItems: "center",
    backgroundColor: "white",
    margin: 5,
    borderRadius: 5,
  },
  iconBackSelected: {
    alignItems: "center",
    backgroundColor: "#0e4e9214",
    margin: 5,
    borderRadius: 5,
    borderColor: colorPrimary,
    borderWidth: 0.6,
  },

  iconBacksort: {
    alignItems: "center",
    backgroundColor: "white",
    margin: 5,
    borderRadius: 5,
  },
  iconBackSelectedsort: {
    alignItems: "center",
    backgroundColor: "#0e4e9214",
    margin: 5,
    borderRadius: 5,
    borderColor: colorPrimary,
    borderWidth: 0.6,
  },
  textInputRowSelected2: {
    height: 50,
    width: "100%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: colorPrimary,
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  textInputRow2: {
    height: 50,
    width: "100%",
    borderWidth: 1,
    paddingHorizontal: 15,
    backgroundColor: "white",
    shadowColor: "rgba(0,0,0, .001)",
    shadowOffset: { height: 0, width: 0 },
    borderColor: "#EBEBEB",
    color: "#343434",
    fontFamily: medium,
    shadowOpacity: 0,
    shadowRadius: 0,
  },
});
